In [1]:
import pandas as pd
import os
path = "C:/Users/Admin/Downloads/data/"
dataframe = pd.read_csv(path +'sales2019_2.csv')
dataframe.head(10)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,150502,iPhone,1,700,02/18/19 01:35,"866 Spruce St, Portland, ME 04101"
1,150503,AA Batteries (4-pack),1,3.84,02/13/19 07:24,"18 13th St, San Francisco, CA 94016"
2,150504,27in 4K Gaming Monitor,1,389.99,02/18/19 09:46,"52 6th St, New York City, NY 10001"
3,150505,Lightning Charging Cable,1,14.95,02/02/19 16:47,"129 Cherry St, Atlanta, GA 30301"
4,150506,AA Batteries (4-pack),2,3.84,02/28/19 20:32,"548 Lincoln St, Seattle, WA 98101"
5,150507,Lightning Charging Cable,1,14.95,02/24/19 18:50,"387 12th St, Austin, TX 73301"
6,150508,AA Batteries (4-pack),1,3.84,02/21/19 19:26,"622 Center St, San Francisco, CA 94016"
7,150509,Apple Airpods Headphones,1,150,02/26/19 19:53,"921 6th St, Seattle, WA 98101"
8,150510,USB-C Charging Cable,1,11.95,02/17/19 21:48,"451 2nd St, Los Angeles, CA 90001"
9,150511,USB-C Charging Cable,1,11.95,02/22/19 07:36,"689 River St, San Francisco, CA 94016"

In [3]:
os.listdir(path)

['.ipynb_checkpoints',
 'DS_Store',
 'import pandas as pd.py',
 'm.py',
 'report.ipynb',
 'sales2019_1.csv',
 'sales2019_10.csv',
 'sales2019_11.csv',
 'sales2019_12.csv',
 'sales2019_2.csv',
 'sales2019_3.csv',
 'sales2019_4.csv',
 'sales2019_5.csv',
 'sales2019_6.csv',
 'sales2019_7.csv',
 'sales2019_8.csv',
 'sales2019_9.csv',
 'Untitled.ipynb']

In [7]:
filepath = []
for file in os.listdir(path):
   if file.endswith('.csv'):
    filepath = path +file
    filepath.append(filepath)
print(filepath)

AttributeError: 'str' object has no attribute 'append'